/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/auth/Login': RouteRecordInfo<
      '/auth/Login',
      '/auth/Login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home/': RouteRecordInfo<
      '/home/',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/': RouteRecordInfo<
      '/user/',
      '/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/[id]': RouteRecordInfo<
      '/user/[id]',
      '/user/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/user/list': RouteRecordInfo<
      '/user/list',
      '/user/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/modules/auth/pages/Login.vue': {
      routes:
        | '/auth/Login'
      views:
        | never
    }
    'src/modules/dashboard/pages/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
    }
    'src/modules/home/pages/index.vue': {
      routes:
        | '/home/'
      views:
        | never
    }
    'src/modules/user/pages/index.vue': {
      routes:
        | '/user/'
      views:
        | never
    }
    'src/modules/user/pages/[id].vue': {
      routes:
        | '/user/[id]'
      views:
        | never
    }
    'src/modules/user/pages/list.vue': {
      routes:
        | '/user/list'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
